### ISSUE TITLE
stackup question

### ISSUE THREAD

**Issue by dotemup** [EnhancedRadioDevices/HamShieldMini#2]
Hi,

I'm looking to get some of these printed and assembled via pcbway for a project.

There is a stackup question though, in the drawing on the gerbers there is a typo for the stackup. Is the standard pcbway stackup okay https://www.pcbway.com/multi-layer-laminated-structure.html?

Or if required for correct impedance control what is the correct core as it is noted to be 47mil?

**Comment by mogar** [comment]
If you clone the repo and open the KiCAD project, you should be able to see the stackup listed on the Cmts.User layer. It was designed around the stackup available from OSHPark for 4-layer boards (as of several years ago, haven't checked since). Here's the stackup:

                Four Layer PCB
 mil           solder resist          +/-0.2mil
1.4 mil     1 oz copper 
6.7 mil     FR408 prepreg       +/-.67mil
0.7 mil     0.5 oz copper 
47 mil      FR408 core            +/-4.7mil
0.7 mil     0.5 oz copper 
6.7 mil     FR408 prepreg       +/-.67mil
1.4 mil     1 oz copper 
1 mil        solder resist           +/-0.2mil

No copper thieving on any layer.
Note split plane on layer 3.
